(function() {var implementors = {};
implementors['libc'] = [];implementors['xcb'] = ["impl&lt;T: <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='xcb/base/struct.Error.html' title='xcb::base::Error'>Error</a>&lt;T&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='xcb/base/enum.ConnError.html' title='xcb::base::ConnError'>ConnError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='xcb/ffi/base/struct.xcb_generic_error_t.html' title='xcb::ffi::base::xcb_generic_error_t'>xcb_generic_error_t</a>",];implementors['xcb'] = ["impl&lt;T: <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='xcb/base/struct.Error.html' title='xcb::base::Error'>Error</a>&lt;T&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='xcb/base/enum.ConnError.html' title='xcb::base::ConnError'>ConnError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='xcb/ffi/base/struct.xcb_generic_error_t.html' title='xcb::ffi::base::xcb_generic_error_t'>xcb_generic_error_t</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
